theme: jekyll-theme-slate
title: welcome to my website!
about me: I'm an electrical engineering student at Princeton University, going into my final year.
I've spent the last two summers interning at Intuitive Surgical, the maker of the Da Vinci surgical system.
There, I've interned for firmware and hardware teams, and learned tons about both fields.
